from __future__ import annotations

import re
import shutil
from pathlib import Path

from pydantic import BaseModel, Field

from sentinel.reliability.subprocess import run_command
from sentinel.schemas.common import SideEffect, ToolStatus
from sentinel.schemas.research import VulnerabilityHypothesis
from sentinel.tools.base import RegisteredTool
from sentinel.tools.repo import RepoPathInput


class DynamicGenericOutput(BaseModel):
    status: ToolStatus
    message: str | None = None
    data: dict = Field(default_factory=dict)


class PocInput(RepoPathInput):
    hypothesis: VulnerabilityHypothesis | None = None
    test_file: str = "test/SentinelGenerated.t.sol"
    test_name: str = "testSentinelGenerated"


def create_poc_test(inp: PocInput, state) -> DynamicGenericOutput:
    hypothesis = inp.hypothesis or (state.get("hypotheses") or [None])[0]
    affected_function = getattr(hypothesis, "affected_functions", [])[:1]
    affected_file = getattr(hypothesis, "affected_files", [])[:1]
    target_function = affected_function[0] if affected_function else "targetFunction"
    target_file = affected_file[0] if affected_file else "src/Target.sol"
    test_source = "\n".join(
        [
            "// SPDX-License-Identifier: MIT",
            "pragma solidity ^0.8.20;",
            "",
            "// Generated by Solidity Sentinel. Review and adapt constructor/setup before relying on this test.",
            f"// Target file: {target_file}",
            f"// Target function: {target_function}",
            "contract SentinelGenerated {",
            f"    function {inp.test_name}() public {{",
            f"        // TODO: instantiate the target and assert unauthorized access to {target_function} is rejected.",
            "        assert(true);",
            "    }",
            "}",
            "",
        ]
    )
    data = {
        "hypothesis_id": getattr(hypothesis, "id", None),
        "test_file": inp.test_file,
        "test_name": inp.test_name,
        "target_file": target_file,
        "target_function": target_function,
        "content": test_source,
    }
    state.setdefault("last_outputs", {})["dynamic.create_poc_test"] = {"status": ToolStatus.OK.value, "data": data}
    return DynamicGenericOutput(status=ToolStatus.OK, data=data)


def patch_poc_test(inp: PocInput, state) -> DynamicGenericOutput:
    generated = state.get("last_outputs", {}).get("dynamic.create_poc_test", {}).get("data", {})
    content = generated.get("content") or create_poc_test(inp, state).data["content"]
    test_file = generated.get("test_file", inp.test_file)
    target = Path(inp.repo_path) / test_file
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    return DynamicGenericOutput(status=ToolStatus.OK, data={"path": str(target), "test_file": test_file})


def run_poc_test(inp: RepoPathInput, state) -> DynamicGenericOutput:
    if shutil.which("forge") is None:
        return DynamicGenericOutput(status=ToolStatus.UNAVAILABLE, message="forge is not installed")
    result = run_command(["forge", "test", "--match-contract", "SentinelGenerated"], cwd=inp.repo_path, timeout=120)
    return DynamicGenericOutput(status=ToolStatus.OK if result.return_code == 0 else ToolStatus.ERROR, data=result.model_dump(mode="json"))


def run_test_verbose(inp: RepoPathInput, state) -> DynamicGenericOutput:
    if shutil.which("forge") is None:
        return DynamicGenericOutput(status=ToolStatus.UNAVAILABLE, message="forge is not installed")
    result = run_command(["forge", "test", "-vvv"], cwd=inp.repo_path, timeout=120)
    return DynamicGenericOutput(status=ToolStatus.OK if result.return_code == 0 else ToolStatus.ERROR, data=result.model_dump(mode="json"))


def parse_test_output(inp: DynamicGenericOutput, state) -> DynamicGenericOutput:
    stdout = str(inp.data.get("stdout", ""))
    stderr = str(inp.data.get("stderr", ""))
    combined = f"{stdout}\n{stderr}"
    passed_count = sum(int(value) for value in re.findall(r"(\d+)\s+passed", combined, flags=re.IGNORECASE))
    failed_counts = [int(value) for value in re.findall(r"(\d+)\s+failed", combined, flags=re.IGNORECASE)]
    failed_count = sum(failed_counts)
    failed = failed_count > 0 or ("FAIL" in combined and not failed_counts)
    passed = passed_count > 0 and not failed
    return DynamicGenericOutput(status=ToolStatus.OK, data={"passed": passed, "failed": failed, "raw_excerpt": combined[-4000:]})


def extract_revert_reason(inp: DynamicGenericOutput, state) -> DynamicGenericOutput:
    text = f"{inp.data.get('stdout', '')}\n{inp.data.get('stderr', '')}\n{inp.data.get('raw_excerpt', '')}"
    matches = re.findall(r"revert(?:ed)?(?: with)?[: ]+([^\n]+)", text, flags=re.IGNORECASE)
    return DynamicGenericOutput(status=ToolStatus.OK, data={"revert_reasons": [match.strip() for match in matches]})


def classify_test_result(inp: DynamicGenericOutput, state) -> DynamicGenericOutput:
    if inp.data.get("passed") is True:
        classification = "poc_passed"
    elif inp.data.get("failed") is True:
        classification = "poc_failed_or_needs_adjustment"
    else:
        classification = "inconclusive"
    return DynamicGenericOutput(status=ToolStatus.OK, data={"classification": classification})


def spawn_poc_subagent(inp: PocInput, state) -> DynamicGenericOutput:
    plan = create_poc_test(inp, state).data
    return DynamicGenericOutput(status=ToolStatus.OK, data={"subagent_kind": "poc_planner", "plan": plan})


def register(registry) -> None:
    specs = [
        ("create_poc_test", "Create a PoC test plan.", PocInput, create_poc_test),
        ("patch_poc_test", "Patch a generated PoC test.", PocInput, patch_poc_test),
        ("run_poc_test", "Run a PoC test.", RepoPathInput, run_poc_test),
        ("run_test_verbose", "Run tests with verbose output.", RepoPathInput, run_test_verbose),
        ("parse_test_output", "Parse test output.", DynamicGenericOutput, parse_test_output),
        ("extract_revert_reason", "Extract revert reasons from test output.", DynamicGenericOutput, extract_revert_reason),
        ("classify_test_result", "Classify test result.", DynamicGenericOutput, classify_test_result),
        ("spawn_poc_subagent", "Spawn a PoC planning subagent.", PocInput, spawn_poc_subagent),
    ]
    for name, description, input_model, fn in specs:
        side_effect = SideEffect.WRITE_FILES if name == "patch_poc_test" else SideEffect.EXECUTE_LOCAL if name.startswith("run_") else SideEffect.NONE
        registry.register(RegisteredTool(namespace="dynamic", name=name, description=description, input_model=input_model, output_model=DynamicGenericOutput, fn=fn, side_effects=[side_effect]))
